name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "container/**"
defaults:
  run:
    working-directory: container
jobs:
  myjob:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
        - run: npm install
        - run: npm run build
